.Function=function() {}
.Error=function() {}
.EvalError=function() {}
.RangeError=function() {}
.ReferenceError=function() {}
.SyntaxError=function() {}
.TypeError=function() {}
.URIError=function() {}
.InternalError=function() {}
.AggregateError=function() {}
.Array=function() {}
.parseInt=function() {}
.parseFloat=function() {}
.isNaN=function() {}
.isFinite=function() {}
.decodeURI=function() {}
.decodeURIComponent=function() {}
.encodeURI=function() {}
.encodeURIComponent=function() {}
.escape=function() {}
.unescape=function() {}
.Infinity=Infinity
.NaN=NaN
.undefined=undefined
.__date_clock=function() {}
.Number=function() {}
.Boolean=function() {}
.String=function() {}
Math.min=function() {}
Math.max=function() {}
Math.abs=function() {}
Math.floor=function() {}
Math.ceil=function() {}
Math.round=function() {}
Math.sqrt=function() {}
Math.acos=function() {}
Math.asin=function() {}
Math.atan=function() {}
Math.atan2=function() {}
Math.cos=function() {}
Math.exp=function() {}
Math.log=function() {}
Math.pow=function() {}
Math.sin=function() {}
Math.tan=function() {}
Math.trunc=function() {}
Math.sign=function() {}
Math.cosh=function() {}
Math.sinh=function() {}
Math.tanh=function() {}
Math.acosh=function() {}
Math.asinh=function() {}
Math.atanh=function() {}
Math.expm1=function() {}
Math.log1p=function() {}
Math.log2=function() {}
Math.log10=function() {}
Math.cbrt=function() {}
Math.hypot=function() {}
Math.random=function() {}
Math.fround=function() {}
Math.imul=function() {}
Math.clz32=function() {}
Math.E=2.718281828459045
Math.LN10=2.302585092994046
Math.LN2=0.6931471805599453
Math.LOG2E=1.4426950408889634
Math.LOG10E=0.4342944819032518
Math.PI=3.141592653589793
Math.SQRT1_2=0.7071067811865476
Math.SQRT2=1.4142135623730951
Reflect.apply=function() {}
Reflect.construct=function() {}
Reflect.defineProperty=function() {}
Reflect.deleteProperty=function() {}
Reflect.get=function() {}
Reflect.getOwnPropertyDescriptor=function() {}
Reflect.getPrototypeOf=function() {}
Reflect.has=function() {}
Reflect.isExtensible=function() {}
Reflect.ownKeys=function() {}
Reflect.preventExtensions=function() {}
Reflect.set=function() {}
Reflect.setPrototypeOf=function() {}
.Symbol=function() {}
.eval=function() {}
.Date=function() {}
.RegExp=function() {}
JSON.parse=function() {}
JSON.stringify=function() {}
.Proxy=function() {}
.Map=function() {}
.Set=function() {}
.WeakMap=function() {}
.WeakSet=function() {}
.ArrayBuffer=function() {}
.SharedArrayBuffer=function() {}
.Uint8ClampedArray=function() {}
.Int8Array=function() {}
.Uint8Array=function() {}
.Int16Array=function() {}
.Uint16Array=function() {}
.Int32Array=function() {}
.Uint32Array=function() {}
.Float32Array=function() {}
.Float64Array=function() {}
.DataView=function() {}
Atomics.add=function() {}
Atomics.and=function() {}
Atomics.or=function() {}
Atomics.sub=function() {}
Atomics.xor=function() {}
Atomics.exchange=function() {}
Atomics.compareExchange=function() {}
Atomics.load=function() {}
Atomics.store=function() {}
Atomics.isLockFree=function() {}
.Promise=function() {}
console.log=function() {}
.print=function() {}
.__loadScript=function() {}
timer.createTimer=function() {}
timer.stopTimer=function() {}
hmApp.action.CLICK=1
hmApp.action.LONG_PRESS=2
hmApp.action.DOUBLE_CLICK=4
hmApp.action.RELEASE=8
hmApp.action.PRESS=16
hmApp.addStatistic=function() {}
hmApp.alarmCancel=function() {}
hmApp.alarmNew=function() {}
hmApp.cancelAlarm=function() {}
hmApp.exit=function() {}
hmApp.gesture.UP=3
hmApp.gesture.DOWN=4
hmApp.gesture.LEFT=2
hmApp.gesture.RIGHT=1
hmApp.getLayerY=function() {}
hmApp.getMemUsage=function() {}
hmApp.getPackageInfo=function() {}
hmApp.goBack=function() {}
hmApp.gotoHome=function() {}
hmApp.gotoPage=function() {}
hmApp.key.BACK=8
hmApp.key.SELECT=13
hmApp.key.HOME=36
hmApp.key.UP=38
hmApp.key.DOWN=40
hmApp.key.SHORTCUT=93
hmApp.newAlarm=function() {}
hmApp.packageInfo=function() {}
hmApp.redirectPage=function() {}
hmApp.registGestureEvent=function() {}
hmApp.registKeyEvent=function() {}
hmApp.registSpinEvent=function() {}
hmApp.registerGestureEvent=function() {}
hmApp.registerKeyEvent=function() {}
hmApp.registerSpinEvent=function() {}
hmApp.reloadPage=function() {}
hmApp.runGC=function() {}
hmApp.setFadeTransition=function() {}
hmApp.setLayerY=function() {}
hmApp.setPathTransition=function() {}
hmApp.setScreenKeep=function() {}
hmApp.startApp=function() {}
hmApp.unregistGestureEvent=function() {}
hmApp.unregistKeyEvent=function() {}
hmApp.unregistSpinEvent=function() {}
hmApp.unregisterGestureEvent=function() {}
hmApp.unregisterKeyEvent=function() {}
hmApp.unregisterSpinEvent=function() {}
hmSetting.getBrightness=function() {}
hmSetting.getDateFormat=function() {}
hmSetting.getDeviceInfo=function() {}
hmSetting.getDiskInfo=function() {}
hmSetting.getLanguage=function() {}
hmSetting.getMileageUnit=function() {}
hmSetting.getRtlLayout=function() {}
hmSetting.getScreenAutoBright=function() {}
hmSetting.getScreenType=function() {}
hmSetting.getSleepTarget=function() {}
hmSetting.getSystemInfo=function() {}
hmSetting.getTemperatureUnit=function() {}
hmSetting.getTimeFormat=function() {}
hmSetting.getUserData=function() {}
hmSetting.getWeightTarget=function() {}
hmSetting.getWeightUnit=function() {}
hmSetting.releasePalmOff=function() {}
hmSetting.releaseWristDownOff=function() {}
hmSetting.screen_type.APP=0
hmSetting.screen_type.WATCHFACE=1
hmSetting.screen_type.SETTINGS=2
hmSetting.screen_type.AOD=3
hmSetting.setBrightScreen=function() {}
hmSetting.setBrightScreenCancel=function() {}
hmSetting.setBrightness=function() {}
hmSetting.setScreenAutoBright=function() {}
hmSetting.setScreenOff=function() {}
hmSetting.setUserDataListener=function() {}
hmSetting.stopPalmOff=function() {}
hmSetting.stopWristDownOff=function() {}
hmUI.align.LEFT=1
hmUI.align.RIGHT=2
hmUI.align.CENTER_H=16
hmUI.align.TOP=4
hmUI.align.BOTTOM=8
hmUI.align.CENTER_V=32
hmUI.anim_status.UNKNOW=0
hmUI.anim_status.START=1
hmUI.anim_status.PAUSE=2
hmUI.anim_status.STOP=3
hmUI.anim_status.RESUME=4
hmUI.checkDataType=function() {}
hmUI.createDialog=function() {}
hmUI.createWidget=function() {}
hmUI.data_type.STEP=1
hmUI.data_type.STEP_TARGET=2
hmUI.data_type.CAL=3
hmUI.data_type.CAL_TARGET=4
hmUI.data_type.HEART=5
hmUI.data_type.PAI_DAILY=6
hmUI.data_type.PAI_WEEKLY=7
hmUI.data_type.HUMIDITY=8
hmUI.data_type.SMS=9
hmUI.data_type.BATTERY=10
hmUI.data_type.WEATHER=11
hmUI.data_type.WEATHER_HIGH_LOW=12
hmUI.data_type.WEATHER_HIGH=13
hmUI.data_type.WEATHER_LOW=14
hmUI.data_type.SUN_SET=16
hmUI.data_type.SUN_RISE=17
hmUI.data_type.SUN_CURRENT=19
hmUI.data_type.SUN_TIME=20
hmUI.data_type.MOON_SET=21
hmUI.data_type.MOON_RISE=22
hmUI.data_type.MOON_CURRENT=23
hmUI.data_type.WIND=24
hmUI.data_type.WIND_DIRECTION=25
hmUI.data_type.TIME=26
hmUI.data_type.UVI=27
hmUI.data_type.BODY_TEMP=28
hmUI.data_type.WEATHER_CURRENT=15
hmUI.data_type.DISTANCE=29
hmUI.data_type.STAND=30
hmUI.data_type.STAND_TARGET=31
hmUI.data_type.SPO2=32
hmUI.data_type.AQI=33
hmUI.data_type.ALTIMETER=34
hmUI.data_type.MOON=35
hmUI.data_type.SUN=18
hmUI.data_type.STRESS=36
hmUI.data_type.FAT_BURN=37
hmUI.data_type.FAT_BURN_TARGET=38
hmUI.data_type.FLOOR=39
hmUI.data_type.COUNT_DOWN=40
hmUI.data_type.STOP_WATCH=41
hmUI.data_type.ALARM_CLOCK=43
hmUI.data_type.SLEEP=42
hmUI.data_type.MENSYRUAL_LEVEL=44
hmUI.data_type.MENSYRUAL=45
hmUI.data_type.WEEK=46
hmUI.data_type.MONTH=47
hmUI.data_type.DAYS_PER_MONTH=48
hmUI.data_type.SYSTEM_STATUS=51
hmUI.data_type.ALTITUDE=53
hmUI.data_type.BARO=52
hmUI.data_type.FATIGUE=54
hmUI.data_type.OUTDOOR_RUNNING=55
hmUI.data_type.WALKING=56
hmUI.data_type.OUTDOOR_CYCLING=57
hmUI.data_type.FREE_TRAINING=58
hmUI.data_type.POOL_SWIMMING=59
hmUI.data_type.OPEN_WATER_SWIMMING=60
hmUI.data_type.TRAINING_LOAD=61
hmUI.data_type.VO2MAX=62
hmUI.data_type.RECOVERY_TIME=63
hmUI.data_type.ACTIVITY=64
hmUI.data_type.ALEXA=65
hmUI.data_type.SBPRESSURE=49
hmUI.data_type.DBPRESSURE=50
hmUI.data_type.FAT_BURNING=37
hmUI.data_type.FAT_BURNING_TARGET=38
hmUI.date.MONTH=0
hmUI.date.DAY=1
hmUI.date.WEEK=2
hmUI.deleteWidget=function() {}
hmUI.edit_type.STEP=10000
hmUI.edit_type.BATTERY=11001
hmUI.edit_type.HEART=10001
hmUI.edit_type.CAL=10006
hmUI.edit_type.DISTANCE=10009
hmUI.edit_type.AQI=10405
hmUI.edit_type.HUMIDITY=10406
hmUI.edit_type.UVI=10407
hmUI.edit_type.DATE=11002
hmUI.edit_type.WEEK=11003
hmUI.edit_type.WEATHER=10401
hmUI.edit_type.TEMPERATURE=10400
hmUI.edit_type.SUN=10408
hmUI.edit_type.STAND=10007
hmUI.edit_type.SUN_RISE=10600
hmUI.edit_type.SUN_SET=10601
hmUI.edit_type.WIND=10409
hmUI.edit_type.SPO2=10002
hmUI.edit_type.STRESS=10003
hmUI.edit_type.FAT_BURN=10008
hmUI.edit_type.FLOOR=10010
hmUI.edit_type.ALTIMETER=10411
hmUI.edit_type.BODY_TEMP=10011
hmUI.edit_type.MOON=10602
hmUI.edit_type.PAI_DAILY=10015
hmUI.edit_type.PAI=10015
hmUI.edit_type.PAI_WEEKLY=10012
hmUI.edit_type.APP_PAI=10013
hmUI.edit_type.SMS=10800
hmUI.edit_type.TIME=11000
hmUI.edit_type.WEATHER_CURRENT=10402
hmUI.edit_type.WEATHER_HIGH=10403
hmUI.edit_type.WEATHER_LOW=10404
hmUI.edit_type.WIND_DIRECTION=10410
hmUI.edit_type.COUNT_DOWN=10801
hmUI.edit_type.STOP_WATCH=10802
hmUI.edit_type.SLEEP=10004
hmUI.edit_type.ALARM_CLOCK=10803
hmUI.edit_type.MENSYRUAL=10005
hmUI.edit_type.TRAINING_LOAD=10200
hmUI.edit_type.VO2MAX=10201
hmUI.edit_type.RECOVERY_TIME=10202
hmUI.edit_type.ALTITUDE=10603
hmUI.edit_type.FATIGUE=10014
hmUI.edit_type.INVALID=11004
hmUI.edit_widget_group_type.FOUNDATION=11000
hmUI.edit_widget_group_type.OUTDOORS=10600
hmUI.edit_widget_group_type.TOOLS=10800
hmUI.edit_widget_group_type.MULTIMEDIA=11200
hmUI.edit_widget_group_type.PAY=11400
hmUI.edit_widget_group_type.HEALTH=10000
hmUI.edit_widget_group_type.SPORTS=10200
hmUI.edit_widget_group_type.WEATHER=10400
hmUI.edit_widget_group_type.OTHERS=11600
hmUI.edit_widget_group_type.INVALID=11800
hmUI.event.MOVE=1
hmUI.event.CLICK_DOWN=2
hmUI.event.CLICK_UP=3
hmUI.event.MOVE_IN=4
hmUI.event.MOVE_OUT=5
hmUI.event.SELECT=6
hmUI.event.GESTURE_RIGHT=257
hmUI.event.GESTURE_LEFT=258
hmUI.event.GESTURE_UP=259
hmUI.event.GESTURE_DOWN=260
hmUI.event.KEY_UP=550
hmUI.event.KEY_DOWN=552
hmUI.getAppWidgetSize=function() {}
hmUI.getImageInfo=function() {}
hmUI.getRtlLayout=function() {}
hmUI.getScrollCurrentPage=function() {}
hmUI.getTextLayout=function() {}
hmUI.prop.MORE=0
hmUI.prop.X=1
hmUI.prop.Y=2
hmUI.prop.W=3
hmUI.prop.H=4
hmUI.prop.POS_X=5
hmUI.prop.POS_Y=6
hmUI.prop.ANGLE=7
hmUI.prop.CENTER_X=8
hmUI.prop.CENTER_Y=9
hmUI.prop.SRC=10
hmUI.prop.TEXT=11
hmUI.prop.COLOR=12
hmUI.prop.COLOR_BG=64
hmUI.prop.START_ANGLE=13
hmUI.prop.END_ANGLE=14
hmUI.prop.LINE_WIDTH=15
hmUI.prop.LINE_START_X=16
hmUI.prop.LINE_START_Y=17
hmUI.prop.LINE_END_X=18
hmUI.prop.LINE_END_Y=19
hmUI.prop.LINE_PROGRESS=20
hmUI.prop.SRC_BG=21
hmUI.prop.SRC_PROGRESS=22
hmUI.prop.SRC_INDICATOR=23
hmUI.prop.ALIGN_H=24
hmUI.prop.ALIGN_V=25
hmUI.prop.IMAGE_ARRAY=26
hmUI.prop.IMAGE_LENGTH=27
hmUI.prop.LEVEL=28
hmUI.prop.TYPE=29
hmUI.prop.TEXT_SIZE=30
hmUI.prop.FONT=31
hmUI.prop.ID=32
hmUI.prop.DATASET=33
hmUI.prop.ANIM_STATUS=34
hmUI.prop.ANIM_IS_RUNINNG=35
hmUI.prop.ANIM_IS_RUNNING=35
hmUI.prop.ANIM_IS_PAUSE=36
hmUI.prop.ANIM_IS_STOP=37
hmUI.prop.ANIM=38
hmUI.prop.RADIUS=39
hmUI.prop.ALPHA=40
hmUI.prop.VISIBLE=41
hmUI.prop.INIT=42
hmUI.prop.CHECKED=43
hmUI.prop.SHOW=44
hmUI.prop.UNCHECKED=45
hmUI.prop.CURRENT_SELECT=46
hmUI.prop.TEXT_STYLE=47
hmUI.prop.CHAR_SPACE=48
hmUI.prop.LINE_SPACE=49
hmUI.prop.END_X=50
hmUI.prop.CURRENT_TYPE=51
hmUI.prop.UPDATE_DATA=52
hmUI.prop.SELECT_INDEX=53
hmUI.prop.CURRENT_CONFIG=54
hmUI.prop.ITEM_MORE=55
hmUI.prop.ITEM_REFRESH=56
hmUI.prop.LIST_TOP=57
hmUI.prop.CORNER_RADIUS=58
hmUI.prop.AUTO_SCALE=59
hmUI.prop.AUTO_SCALE_OBJ_FIT=60
hmUI.prop.ANIM_STEP=61
hmUI.prop.ANIM_FRAME_CUR_INDEX=62
hmUI.prop.ANIM_PLAY_BACK=63
hmUI.prop.UPDATE_ITEM=65
hmUI.prop.DELETE_ITEM=66
hmUI.prop.MOVE_ITEM=67
hmUI.redraw=function() {}
hmUI.relayoutRtl=function() {}
hmUI.scrollToPage=function() {}
hmUI.setAppWidgetSize=function() {}
hmUI.setLayerScrolling=function() {}
hmUI.setScrollView=function() {}
hmUI.setStatusBarVisible=function() {}
hmUI.showToast=function() {}
hmUI.show_level.ALL=7
hmUI.show_level.ONLY_NORMAL=1
hmUI.show_level.ONAL_AOD=2
hmUI.show_level.ONLY_AOD=2
hmUI.show_level.ONLY_EDIT=4
hmUI.system_status.DISCONNECT=0
hmUI.system_status.DISTURB=1
hmUI.system_status.LOCK=2
hmUI.system_status.CLOCK=3
hmUI.text_style.CHAR_WRAP=0
hmUI.text_style.WRAP=1
hmUI.text_style.ELLIPSIS=2
hmUI.text_style.NONE=3
hmUI.updateStatusBarTitle=function() {}
hmUI.widget.IMG=1
hmUI.widget.GROUP=65536
hmUI.widget.TEXT=2
hmUI.widget.ARC=3
hmUI.widget.FILL_RECT=4
hmUI.widget.STROKE_RECT=5
hmUI.widget.TEXT_IMG=6
hmUI.widget.ARC_PROGRESS=7
hmUI.widget.LINE_PROGRESS=8
hmUI.widget.IMG_PROGRESS=9
hmUI.widget.IMG_LEVEL=10
hmUI.widget.IMG_GROUP=41
hmUI.widget.IMG_POINTER=11
hmUI.widget.IMG_DATE=13
hmUI.widget.IMG_WEEK=14
hmUI.widget.IMG_TIME=12
hmUI.widget.IMG_ANIM=15
hmUI.widget.IMG_STATUS=16
hmUI.widget.IMG_CLICK=17
hmUI.widget.IMG_FILL=42
hmUI.widget.TEXT_TIME=18
hmUI.widget.TIME_NUM=19
hmUI.widget.CYCLE_LIST=20
hmUI.widget.CIRCLE=21
hmUI.widget.STATE_BUTTON=22
hmUI.widget.RADIO_GROUP=65537
hmUI.widget.CHECKBOX_GROUP=65538
hmUI.widget.BUTTON=23
hmUI.widget.SLIDE_SWITCH=24
hmUI.widget.DIALOG=25
hmUI.widget.SCROLL_LIST=26
hmUI.widget.VIEW_CONTAINER=768
hmUI.widget.CYCLE_IMAGE_TEXT_LIST=27
hmUI.widget.TIME_POINTER=28
hmUI.widget.WATCHFACE_EDIT_MASK=29
hmUI.widget.WATCHFACE_EDIT_FG_MASK=30
hmUI.widget.WATCHFACE_EDIT_GROUP=65539
hmUI.widget.WATCHFACE_EDIT_BG=31
hmUI.widget.HISTOGRAM=32
hmUI.widget.DATE_POINTER=33
hmUI.widget.TEXT_FONT=34
hmUI.widget.WIDGET_DELEGATE=35
hmUI.widget.GRADKIENT_POLYLINE=36
hmUI.widget.PICK_TIME=512
hmUI.widget.PICK_DATE=513
hmUI.widget.WATCHFACE_EDIT_POINTER=65540
hmUI.widget.ARC_PROGRESS_FILL=37
hmUI.widget.QRCODE=38
hmUI.widget.BARCODE=39
hmUI.widget.PAGE_INDICATOR=40
hmUI.widget.WATCHFACE_EDIT_TIME=65541
hmSensor.createSensor=function() {}
hmSensor.event.DELAY=0
hmSensor.event.CHANGE=1
hmSensor.id.BATTERY=10
hmSensor.id.STEP=11
hmSensor.id.CALORIE=12
hmSensor.id.HEART=13
hmSensor.id.PAI=14
hmSensor.id.DISTANCE=15
hmSensor.id.STAND=16
hmSensor.id.WEATHER=17
hmSensor.id.ACTIVITY=18
hmSensor.id.FAT_BURRING=19
hmSensor.id.FAT_BURNING=19
hmSensor.id.SUN=20
hmSensor.id.WIND=21
hmSensor.id.STRESS=22
hmSensor.id.SPO2=23
hmSensor.id.BODY_TEMP=24
hmSensor.id.PRESS=25
hmSensor.id.TIME=26
hmSensor.id.VIBRATE=27
hmSensor.id.WEAR=28
hmSensor.id.WORLD_CLOCK=29
hmSensor.id.MUSIC=30
hmSensor.id.SLEEP=31
hmSensor.id.SPORT=32
hmSensor.id.BPRESSURE=33
hmFS.O_APPEND=1024
hmFS.O_CREAT=64
hmFS.O_EXCL=128
hmFS.O_RDONLY=0
hmFS.O_RDWR=2
hmFS.O_TRUNC=512
hmFS.O_WRONLY=1
hmFS.SEEK_CUR=1
hmFS.SEEK_END=2
hmFS.SEEK_SET=0
hmFS.SharedpAppend=function() {}
hmFS.SharedpClose=function() {}
hmFS.SharedpDeleteKey=function() {}
hmFS.SharedpGet=function() {}
hmFS.SharedpGetSize=function() {}
hmFS.SharedpOpen=function() {}
hmFS.SharedpSet=function() {}
hmFS.SharedpUpdate=function() {}
hmFS.SysProGetBool=function() {}
hmFS.SysProGetChars=function() {}
hmFS.SysProGetDouble=function() {}
hmFS.SysProGetInt=function() {}
hmFS.SysProGetInt64=function() {}
hmFS.SysProSetBool=function() {}
hmFS.SysProSetChars=function() {}
hmFS.SysProSetDouble=function() {}
hmFS.SysProSetInt=function() {}
hmFS.SysProSetInt64=function() {}
hmFS.close=function() {}
hmFS.mkdir=function() {}
hmFS.open=function() {}
hmFS.open_asset=function() {}
hmFS.read=function() {}
hmFS.readdir=function() {}
hmFS.remove=function() {}
hmFS.rename=function() {}
hmFS.seek=function() {}
hmFS.stat=function() {}
hmFS.stat_asset=function() {}
hmFS.write=function() {}
hmBle.addFWListener=function() {}
hmBle.addListener=function() {}
hmBle.cancelTransferFile=function() {}
hmBle.connectStatus=function() {}
hmBle.createConnect=function() {}
hmBle.disConnect=function() {}
hmBle.getAddress=function() {}
hmBle.mstBuildProfile=function() {}
hmBle.mstConnect=function() {}
hmBle.mstDestoryProfileInstance=function() {}
hmBle.mstDisconnect=function() {}
hmBle.mstOffAllCb=function() {}
hmBle.mstOnCharaNotification=function() {}
hmBle.mstOnCharaReadComplete=function() {}
hmBle.mstOnCharaValueArrived=function() {}
hmBle.mstOnCharaWriteComplete=function() {}
hmBle.mstOnDescReadComplete=function() {}
hmBle.mstOnDescValueArrived=function() {}
hmBle.mstOnDescWriteComplete=function() {}
hmBle.mstOnPrepare=function() {}
hmBle.mstOnServiceChangeBegin=function() {}
hmBle.mstOnServiceChangeEnd=function() {}
hmBle.mstPair=function() {}
hmBle.mstPrepare=function() {}
hmBle.mstReadCharacteristic=function() {}
hmBle.mstReadDescriptor=function() {}
hmBle.mstStartScan=function() {}
hmBle.mstStopScan=function() {}
hmBle.mstWriteCharacteristic=function() {}
hmBle.mstWriteDescriptor=function() {}
hmBle.removeFWListener=function() {}
hmBle.removeListener=function() {}
hmBle.send=function() {}
hmBle.transferFile=function() {}
hmMedia.codec.SILK=0
hmMedia.codec.OPUS=1
hmMedia.create=function() {}
hmMedia.id.RECORDER=1
hmMedia.id.PLAYER=2
__$$hmAppManager$$__.currentApp.pid=3
__$$hmAppManager$$__.currentApp.__globals__.lang.lang=en-US
__$$hmAppManager$$__.currentApp.__globals__.px=function() {}
__$$hmAppManager$$__.currentApp.__globals__.gettext=function() {}
__$$hmAppManager$$__.currentApp.app._options.onCreate=function() {}
__$$hmAppManager$$__.currentApp.app._options.onDestroy=function() {}
__$$hmAppManager$$__.currentApp.app.onCreate=function() {}
__$$hmAppManager$$__.currentApp.app.onDestroy=function() {}
__$$hmAppManager$$__.currentApp.app.onError=function() {}
__$$hmAppManager$$__.currentApp.app.onPageNotFound=function() {}
__$$hmAppManager$$__.currentApp.app.onUnhandledRejection=function() {}
__$$hmAppManager$$__.currentApp.current.id=1
DeviceRuntimeCore.App=function() {}
DeviceRuntimeCore.AppEvent=function() {}
DeviceRuntimeCore.AppWidget=function() {}
DeviceRuntimeCore.Buffer=function() {}
DeviceRuntimeCore.Build.version=2.0
DeviceRuntimeCore.Build.compareVersion=function() {}
DeviceRuntimeCore.Build.runtime.version=2.0.0-200
DeviceRuntimeCore.Build.runtime.buildDate=2022-08-19T15:02:21.162Z
DeviceRuntimeCore.Build.runtime.commit=5584bae
DeviceRuntimeCore.FileTransfer=function() {}
DeviceRuntimeCore.Globals.getGlobalObject=function() {}
DeviceRuntimeCore.Globals.extensibleFreeze=function() {}
DeviceRuntimeCore.Globals.freezeGlobal=function() {}
DeviceRuntimeCore.HmDomApi=function() {}
DeviceRuntimeCore.HmLogger.prefix=jsrt-2.0.0-200
DeviceRuntimeCore.HmLogger.appId=-1
DeviceRuntimeCore.HmLogger.tag=-
DeviceRuntimeCore.HmLogger.levels.all=5e-324
DeviceRuntimeCore.HmLogger.levels.log=1
DeviceRuntimeCore.HmLogger.levels.debug=2
DeviceRuntimeCore.HmLogger.levels.info=3
DeviceRuntimeCore.HmLogger.levels.warn=4
DeviceRuntimeCore.HmLogger.levels.error=5
DeviceRuntimeCore.HmLogger.levels.off=1.7976931348623157e+308
DeviceRuntimeCore.HmLogger.line=1
DeviceRuntimeCore.HmLogger._loggerMap.file-transfer.prefix=jsrt-2.0.0-200
DeviceRuntimeCore.HmLogger._loggerMap.file-transfer.appId=-1
DeviceRuntimeCore.HmLogger._loggerMap.file-transfer.tag=-
DeviceRuntimeCore.HmLogger._loggerMap.file-transfer.line=1
DeviceRuntimeCore.HmLogger._loggerMap.file-transfer.name=file-transfer
DeviceRuntimeCore.HmLogger._loggerMap.file-transfer._level=5e-324
DeviceRuntimeCore.HmLogger._loggerMap.file-transfer._log=function() {}
DeviceRuntimeCore.HmLogger._loggerMap.hmble-dispatch.prefix=jsrt-2.0.0-200
DeviceRuntimeCore.HmLogger._loggerMap.hmble-dispatch.appId=-1
DeviceRuntimeCore.HmLogger._loggerMap.hmble-dispatch.tag=-
DeviceRuntimeCore.HmLogger._loggerMap.hmble-dispatch.line=1
DeviceRuntimeCore.HmLogger._loggerMap.hmble-dispatch.name=hmble-dispatch
DeviceRuntimeCore.HmLogger._loggerMap.hmble-dispatch._level=5e-324
DeviceRuntimeCore.HmLogger._loggerMap.hmble-dispatch._log=function() {}
DeviceRuntimeCore.HmLogger._loggerMap.framework.prefix=jsrt-2.0.0-200
DeviceRuntimeCore.HmLogger._loggerMap.framework.appId=-1
DeviceRuntimeCore.HmLogger._loggerMap.framework.tag=-
DeviceRuntimeCore.HmLogger._loggerMap.framework.line=1
DeviceRuntimeCore.HmLogger._loggerMap.framework.name=framework
DeviceRuntimeCore.HmLogger._loggerMap.framework._level=5e-324
DeviceRuntimeCore.HmLogger._loggerMap.framework._log=function() {}
DeviceRuntimeCore.HmLogger._loggerMap.__invoke__.prefix=jsrt-2.0.0-200
DeviceRuntimeCore.HmLogger._loggerMap.__invoke__.appId=-1
DeviceRuntimeCore.HmLogger._loggerMap.__invoke__.tag=-
DeviceRuntimeCore.HmLogger._loggerMap.__invoke__.line=1
DeviceRuntimeCore.HmLogger._loggerMap.__invoke__.name=__invoke__
DeviceRuntimeCore.HmLogger._loggerMap.__invoke__._level=5e-324
DeviceRuntimeCore.HmLogger._loggerMap.__invoke__._log=function() {}
DeviceRuntimeCore.HmLogger._loggerMap.sanjiao.prefix=jsrt-2.0.0-200
DeviceRuntimeCore.HmLogger._loggerMap.sanjiao.appId=-1
DeviceRuntimeCore.HmLogger._loggerMap.sanjiao.tag=-
DeviceRuntimeCore.HmLogger._loggerMap.sanjiao.line=1
DeviceRuntimeCore.HmLogger._loggerMap.sanjiao.name=sanjiao
DeviceRuntimeCore.HmLogger._loggerMap.sanjiao._level=5e-324
DeviceRuntimeCore.HmLogger._loggerMap.sanjiao._log=function() {}
DeviceRuntimeCore.HmLogger.name=js-app
DeviceRuntimeCore.HmLogger._level=5e-324
DeviceRuntimeCore.HmLogger._log=function() {}
DeviceRuntimeCore.HmSensorApi=function() {}
DeviceRuntimeCore.HmSetting.getLanguage=function() {}
DeviceRuntimeCore.HmUtils.noop=function() {}
DeviceRuntimeCore.HmUtils.mergeProps=function() {}
DeviceRuntimeCore.HmUtils.isDef=function() {}
DeviceRuntimeCore.HmUtils.isArray=function() {}
DeviceRuntimeCore.HmUtils.isString=function() {}
DeviceRuntimeCore.HmUtils.isInteger=function() {}
DeviceRuntimeCore.HmUtils.isObjectLike=function() {}
DeviceRuntimeCore.HmUtils.isPlainObject=function() {}
DeviceRuntimeCore.HmUtils.isBuffer=function() {}
DeviceRuntimeCore.HmUtils.isFunction=function() {}
DeviceRuntimeCore.HmUtils.getTextHeight=function() {}
DeviceRuntimeCore.HmUtils.measureTextWidth=function() {}
DeviceRuntimeCore.HmUtils.urlEncode=function() {}
DeviceRuntimeCore.HmUtils.urlDecode=function() {}
DeviceRuntimeCore.HmUtils.getAppJson=function() {}
DeviceRuntimeCore.HmUtils.getDeviceInfo=function() {}
DeviceRuntimeCore.HmUtils.getPx=function() {}
DeviceRuntimeCore.HmUtils.toHexAppId=function() {}
DeviceRuntimeCore.HmUtils.pipe=function() {}
DeviceRuntimeCore.HmUtils.partialRight=function() {}
DeviceRuntimeCore.HmUtils.getContext=function() {}
DeviceRuntimeCore.HmUtils.convertMileSecondToSecond=function() {}
DeviceRuntimeCore.HmUtils.processStringObj=function() {}
DeviceRuntimeCore.HmUtils.processConstants=function() {}
DeviceRuntimeCore.HmUtils.isArrayBuffer=function() {}
DeviceRuntimeCore.HmUtils.ab2str=function() {}
DeviceRuntimeCore.HmUtils.memoize=function() {}
DeviceRuntimeCore.HmUtils.uniq=function() {}
DeviceRuntimeCore.HmUtils.format=function() {}
DeviceRuntimeCore.HmUtils.gettextFactory=function() {}
DeviceRuntimeCore.HmUtils.Lang=function() {}
DeviceRuntimeCore.HmUtils.getLanguage=function() {}
DeviceRuntimeCore.LifeCycle.beforeAppCreate=function() {}
DeviceRuntimeCore.LifeCycle.afterAppCreate=function() {}
DeviceRuntimeCore.LifeCycle.beforeModuleCreate=function() {}
DeviceRuntimeCore.LifeCycle.afterModuleCreate=function() {}
DeviceRuntimeCore.LifeCycle.beforePageCreate=function() {}
DeviceRuntimeCore.LifeCycle.afterPageCreate=function() {}
DeviceRuntimeCore.LifeCycle.onAppError=function() {}
DeviceRuntimeCore.Page=function() {}
DeviceRuntimeCore.ProxySandbox=function() {}
DeviceRuntimeCore.SecondaryWidget=function() {}
DeviceRuntimeCore.SensorWidgetFactory=function() {}
DeviceRuntimeCore.WatchFace=function() {}
DeviceRuntimeCore.WatchWidget=function() {}
DeviceRuntimeCore.WidgetFactory=function() {}
DeviceRuntimeCore.__init__=function() {}
DeviceRuntimeCore.__invoke__=function() {}
DeviceRuntimeCore.buildDate=2022-08-19T15:02:21.077Z
DeviceRuntimeCore.commit=5584bae
DeviceRuntimeCore.executeScript=function() {}
DeviceRuntimeCore.version=2.0.0-200
DeviceRuntimeCore.__esModule=true
.Buffer=function() {}
.clearTimeout=function() {}
.setTimeout=function() {}
.clearImmediate=function() {}
.setImmediate=function() {}
.clearInterval=function() {}
.setInterval=function() {}
.App=function() {}
.Page=function() {}
mask.setProperty=function() {}
mask.getProperty=function() {}
mask.getId=function() {}
mask.getType=function() {}
mask.getPropertyKey=function() {}
mask.addEventListener=function() {}
mask.removeEventListener=function() {}
mask.layoutChange=function() {}
mask.setEnable=function() {}
mask.setColor=function() {}
mask.setAlpha=function() {}

